New number mask using toLocaleString
clutchcanada/helpers pull request #57
Opened 2021-03-08 22:01 UTC by jordanCain

2021-03-08 22:07 UTC, rhamzeh requested changes

2021-03-08 22:07 UTC, rhamzeh commented on src/numberMask/index.js
> +  if (value === null || value === 0 || value === '') return 0;
Can we just say

```
if (!value) { ... }
```

I feel if value is false or undefined, we want to also return 0

2021-03-16 13:24 UTC, jordanCain commented on src/numberMask/index.js
> +  const valueAsNumber = parseFloat(value);
Problem with parseFlow/parseInt is that if a string is passed in by mistake the parsing will end at the first none numerical character, e.g `9,999` would be parsed as `9`

2021-03-16 13:27 UTC, jordanCain commented on src/numberMask/index.js
> +  const valueAsNumber = parseFloat(value);
We could cast the input parameter to a string and then try and do a regex replace of [non numeric, '.', '-'], if we did this we would need the same previous regex used to track for negative numbers I think ```const numberValue = isNegative ? `-${removeNonNumeric(R.tail(stringValue))}` : removeNonNumeric(stringValue);``` due to lack of browser compatibility with negative look behind regex

2021-03-31 19:48 UTC, jordanCain commented on src/numberMask/index.js
> +  const valueAsNumber = parseFloat(value);
If we just tried to remove all non numeric values first we would run the risk of modifying a string that gets passed in such as "-1" and returning "1"

2021-03-31 22:12 UTC, rhamzeh requested changes

2021-03-31 22:12 UTC, rhamzeh commented on src/numberMask/index.js
> +  if (!value) return '';
This PR is almost 💯 

But minor thing, if `value === 0` we need to return `0` not an empty string

2021-04-01 12:56 UTC, rhamzeh approved these changes

2021-04-01 14:32 UTC, merged

2021-04-01 19:26 UTC, ClutchCanadaCI commented
This issue has been resolved in version [1.22.0-develop.1](<github_release_url>)

2021-04-07 15:59 UTC, ClutchCanadaCI commented
This issue has been resolved in version [1.22.0](<github_release_url>)